server:
  port: 7777

spring:
  jackson:
    serialization:
      wrap_root_value: true

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/REALWORLD
    username: root
    password: 1111

image:
  default: https://static.productionready.io/images/smiley-cyrus.jpg

jwt:
  secret: nRvyYC4soFxBdZ-F-5Nnzz5USXstR1YylsTd-mA0aKtI9HUlriGrtkf-TiuDapkLiUCogO3JOK7kwZisrHp6wA
  sessionTime: 86400

